; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-n16r8]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
build_flags = 
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DBOARD_HAS_PSRAM
monitor_speed = 115200
lib_deps = 
	https://github.com/esp32beans/ESP32_USB_Host_HID/archive/e5cc02275155ddfa8a3d087a8094a865b5d07b17.zip
	fastled/FastLED@^3.10.3
	esp32async/ESPAsyncWebServer@^3.11.0
	esp32async/AsyncTCP@^3.4.10
	bblanchon/ArduinoJson@^7.2.2
